# Generated by Django 4.2.26 on 2025-12-03 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('COORDENADOR', 'Coordenador')], max_length=20, verbose_name='Tipo de papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_funcional', models.CharField(max_length=20, unique=True, verbose_name='Código Funcional')),
                ('formacao', models.CharField(blank=True, max_length=100, verbose_name='Formação')),
                ('papel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_info', to='pessoas.papel')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='papel',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to='pessoas.pessoa'),
        ),
        migrations.CreateModel(
            name='AlunoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('data_ingresso', models.DateField(auto_now_add=True, verbose_name='Data de ingresso')),
                ('papel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_info', to='pessoas.papel')),
            ],
        ),
    ]
