# Generated by Django 4.2.25 on 2025-10-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunoinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='papel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professorinfo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='papel',
            unique_together=set(),
        ),
    ]
