# Generated by Django 4.2.27 on 2025-12-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoinfo',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matrícula'),
        ),
    ]
