# Generated by Django 4.2.26 on 2025-11-27 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0002_alter_alunoinfo_options_alter_papel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
