# Generated by Django 4.2.26 on 2025-12-03 17:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('POR', 'Língua Portuguesa'), ('MAT', 'Matemática'), ('CIE', 'Ciências'), ('HIS', 'História'), ('GEO', 'Geografia'), ('ING', 'Inglês'), ('ART', 'Artes'), ('EDF', 'Educação Física')], max_length=3, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.IntegerField(default=80, verbose_name='Carga horária (horas)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Disciplina ativa')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='pessoas.professorinfo', verbose_name='Professor responsável')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(default=django.utils.timezone.now, verbose_name='Data de matrícula')),
                ('situacao', models.CharField(choices=[('ATIVA', 'Ativa'), ('TRANCADA', 'Trancada'), ('CANCELADA', 'Cancelada'), ('TRANSFERIDA', 'Transferida')], default='ATIVA', max_length=15, verbose_name='Situação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Matrícula ativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='pessoas.alunoinfo', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_matricula'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('serie', models.CharField(choices=[('1ANO', '1º Ano'), ('2ANO', '2º Ano'), ('3ANO', '3º Ano'), ('4ANO', '4º Ano'), ('5ANO', '5º Ano'), ('6ANO', '6º Ano'), ('7ANO', '7º Ano'), ('8ANO', '8º Ano'), ('9ANO', '9º Ano')], max_length=4, verbose_name='Série')),
                ('periodo', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('INTEGRAL', 'Integral')], max_length=10, verbose_name='Período')),
                ('ano_letivo', models.IntegerField(default=2025, verbose_name='Ano letivo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Turma ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(related_name='turmas', through='academico.Matricula', to='pessoas.alunoinfo', verbose_name='Alunos')),
                ('disciplinas', models.ManyToManyField(related_name='turmas', to='academico.disciplina', verbose_name='Disciplinas')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='pessoas.professorinfo', verbose_name='Professor responsável')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['ano_letivo', 'serie', 'nome'],
                'unique_together': {('nome', 'ano_letivo')},
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], verbose_name='Bimestre')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de lançamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pessoas.alunoinfo', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.disciplina', verbose_name='Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['turma', 'disciplina', 'bimestre', 'aluno'],
                'unique_together': {('aluno', 'disciplina', 'turma', 'bimestre')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('total_aulas', models.IntegerField(default=0, verbose_name='Total de aulas')),
                ('total_presencas', models.IntegerField(default=0, verbose_name='Total de presenças')),
                ('total_faltas', models.IntegerField(default=0, verbose_name='Total de faltas')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='pessoas.alunoinfo', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='academico.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['ano', 'mes', 'aluno'],
                'unique_together': {('aluno', 'turma', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='pessoas.alunoinfo', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='academico.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
                'ordering': ['data', 'aluno'],
                'unique_together': {('turma', 'aluno', 'data')},
            },
        ),
    ]
