# Generated by Django 4.2.26 on 2025-11-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='sala',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
